# Generated by Django 6.0 on 2026-01-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transactions', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('fraud_result', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
