# Generated by Django 6.0 on 2026-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='fraud_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
